package proyect.avance.sistemaventa.vista;

import proyect.avance.sistemaventa.controladorAdministrador.RegistroUsuariosControlador;
import proyect.avance.sistemaventa.utils.Utilitarios;

/**
 *
 * @author Juan Carlos Estevez Vargas
 */
public class RegistroUsuarios extends javax.swing.JFrame {

    private final RegistroUsuariosControlador registroUsuariosControlador;
    private final boolean esRegistroUsuarios;

    public RegistroUsuarios(boolean esRegistroUusarios) {
       this.registroUsuariosControlador = RegistroUsuariosControlador.getInstance();
        initComponents();
        this.setLocationRelativeTo(null);
        this.esRegistroUsuarios =  esRegistroUusarios;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                panelLogin = new javax.swing.JPanel();
                labelInicio = new javax.swing.JLabel();
                labelCorreoElectronicoUsuario = new javax.swing.JLabel();
                txtNombreUsuario = new javax.swing.JTextField();
                labelPasswordUsuario = new javax.swing.JLabel();
                txtPasswordUsuario = new javax.swing.JPasswordField();
                btnRegistrarse = new javax.swing.JButton();
                labelNombreUsuario = new javax.swing.JLabel();
                txtCorreoUsuario = new javax.swing.JTextField();
                labelRlUsuario = new javax.swing.JLabel();
                cmbRolUsuario = new javax.swing.JComboBox<>();
                Fondo = new javax.swing.JPanel();
                labelLogo = new javax.swing.JLabel();
                labelTituloRegistrarUsuario = new javax.swing.JLabel();
                labelDesarrolladoPorEnRegistrarUsuario = new javax.swing.JLabel();
                labelNombreDesarrolladorEnRegistrarUsuario = new javax.swing.JLabel();
                labelTituloVersionEnRegistrarUsuario = new javax.swing.JLabel();
                labelContactoEnRegistrarUsuario = new javax.swing.JLabel();
                labelEmailDesarrolladorRegistrarUsuario = new javax.swing.JLabel();
                imagenFondo = new javax.swing.JLabel();
                imagenFondo1 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                panelLogin.setBackground(new java.awt.Color(255, 255, 255));
                panelLogin.setForeground(new java.awt.Color(51, 51, 51));

                labelInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juan/estevez/sistemaventa/img/iniciar.png"))); // NOI18N

                labelCorreoElectronicoUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                labelCorreoElectronicoUsuario.setForeground(new java.awt.Color(51, 51, 51));
                labelCorreoElectronicoUsuario.setText("Correo Electrónico");

                txtNombreUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);

                labelPasswordUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                labelPasswordUsuario.setForeground(new java.awt.Color(51, 51, 51));
                labelPasswordUsuario.setText("Password");

                txtPasswordUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);

                btnRegistrarse.setBackground(new java.awt.Color(0, 51, 102));
                btnRegistrarse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                btnRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
                btnRegistrarse.setText("Registrarse");
                btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRegistrarseActionPerformed(evt);
                        }
                });

                labelNombreUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                labelNombreUsuario.setForeground(new java.awt.Color(51, 51, 51));
                labelNombreUsuario.setText("Nombre");

                txtCorreoUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);

                labelRlUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                labelRlUsuario.setForeground(new java.awt.Color(51, 51, 51));
                labelRlUsuario.setText("Rol");

                cmbRolUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Asistente" }));
                cmbRolUsuario.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cmbRolUsuarioActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
                panelLogin.setLayout(panelLoginLayout);
                panelLoginLayout.setHorizontalGroup(
                        panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelLoginLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelRlUsuario)
                                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(labelNombreUsuario)
                                                .addComponent(labelPasswordUsuario)
                                                .addComponent(labelCorreoElectronicoUsuario)
                                                .addComponent(txtNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                                                .addComponent(txtPasswordUsuario)
                                                .addComponent(txtCorreoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                                        .addComponent(cmbRolUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(32, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                                .addContainerGap(111, Short.MAX_VALUE)
                                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                                                .addComponent(labelInicio)
                                                .addGap(110, 110, 110))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                                                .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(91, 91, 91))))
                );
                panelLoginLayout.setVerticalGroup(
                        panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelLoginLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(labelInicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelCorreoElectronicoUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCorreoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(labelPasswordUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPasswordUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelNombreUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelRlUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbRolUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(41, Short.MAX_VALUE))
                );

                getContentPane().add(panelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 320, 380));

                Fondo.setBackground(new java.awt.Color(0, 102, 102));

                labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juan/estevez/sistemaventa/img/logo.png"))); // NOI18N

                labelTituloRegistrarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                labelTituloRegistrarUsuario.setForeground(new java.awt.Color(255, 255, 255));
                labelTituloRegistrarUsuario.setText("REGISTRO");

                labelDesarrolladoPorEnRegistrarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                labelDesarrolladoPorEnRegistrarUsuario.setForeground(new java.awt.Color(204, 204, 204));

                labelNombreDesarrolladorEnRegistrarUsuario.setForeground(new java.awt.Color(204, 204, 204));

                labelTituloVersionEnRegistrarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                labelTituloVersionEnRegistrarUsuario.setForeground(new java.awt.Color(204, 204, 204));

                labelContactoEnRegistrarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                labelContactoEnRegistrarUsuario.setForeground(new java.awt.Color(204, 204, 204));
                labelContactoEnRegistrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyect/avance/sistemaventa/img/ingreso.png"))); // NOI18N

                labelEmailDesarrolladorRegistrarUsuario.setForeground(new java.awt.Color(204, 204, 204));

                javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
                Fondo.setLayout(FondoLayout);
                FondoLayout.setHorizontalGroup(
                        FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FondoLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelEmailDesarrolladorRegistrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(FondoLayout.createSequentialGroup()
                                                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(FondoLayout.createSequentialGroup()
                                                                .addComponent(labelLogo)
                                                                .addGap(128, 128, 128))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                                                                .addComponent(labelTituloVersionEnRegistrarUsuario)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(labelTituloRegistrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(labelContactoEnRegistrarUsuario))
                                                                .addGap(90, 90, 90)))
                                                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(labelDesarrolladoPorEnRegistrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(FondoLayout.createSequentialGroup()
                                                                .addGap(62, 62, 62)
                                                                .addComponent(labelNombreDesarrolladorEnRegistrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                FondoLayout.setVerticalGroup(
                        FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FondoLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(labelLogo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelDesarrolladoPorEnRegistrarUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelTituloRegistrarUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelNombreDesarrolladorEnRegistrarUsuario)
                                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(FondoLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelTituloVersionEnRegistrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(FondoLayout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(labelContactoEnRegistrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(97, 97, 97)
                                .addComponent(labelEmailDesarrolladorRegistrarUsuario)
                                .addGap(26, 26, 26))
                );

                getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 380));

                imagenFondo.setBackground(new java.awt.Color(255, 255, 255));
                imagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juan/estevez/sistemaventa/img/login.jpg"))); // NOI18N
                getContentPane().add(imagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 150, 430));

                imagenFondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyect/avance/sistemaventa/img/login.jpg"))); // NOI18N
                getContentPane().add(imagenFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 330, 410));

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        String correo = Utilitarios.eliminarEspaciosEnBlanco(txtCorreoUsuario.getText());
        String password = Utilitarios.eliminarEspaciosEnBlanco(String.valueOf(txtPasswordUsuario.getPassword()));
        String nombre = Utilitarios.eliminarEspaciosEnBlanco(txtNombreUsuario.getText());
        String rol = cmbRolUsuario.getSelectedItem().toString();

        if (registroUsuariosControlador.validar(correo, password, nombre, rol, esRegistroUsuarios)) {
            this.dispose();
        }
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void cmbRolUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRolUsuarioActionPerformed
    }//GEN-LAST:event_cmbRolUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new RegistroUsuarios(false).setVisible(true);
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel Fondo;
        private javax.swing.JButton btnRegistrarse;
        private javax.swing.JComboBox<String> cmbRolUsuario;
        private javax.swing.JLabel imagenFondo;
        private javax.swing.JLabel imagenFondo1;
        private javax.swing.JLabel labelContactoEnRegistrarUsuario;
        private javax.swing.JLabel labelCorreoElectronicoUsuario;
        private javax.swing.JLabel labelDesarrolladoPorEnRegistrarUsuario;
        private javax.swing.JLabel labelEmailDesarrolladorRegistrarUsuario;
        private javax.swing.JLabel labelInicio;
        private javax.swing.JLabel labelLogo;
        private javax.swing.JLabel labelNombreDesarrolladorEnRegistrarUsuario;
        private javax.swing.JLabel labelNombreUsuario;
        private javax.swing.JLabel labelPasswordUsuario;
        private javax.swing.JLabel labelRlUsuario;
        private javax.swing.JLabel labelTituloRegistrarUsuario;
        private javax.swing.JLabel labelTituloVersionEnRegistrarUsuario;
        private javax.swing.JPanel panelLogin;
        private javax.swing.JTextField txtCorreoUsuario;
        private javax.swing.JTextField txtNombreUsuario;
        private javax.swing.JPasswordField txtPasswordUsuario;
        // End of variables declaration//GEN-END:variables
}
